### ISSUE TITLE
windows version not send message to chat groud

### ISSUE THREAD

**Issue by Titintgn** [7orlum/SmtpTelegramGateway#6]
Good morning, I have tried the Windows 1.3 version and there is no way to send the message to the group. It recognizes the message. It accepts the token but does not send it to the group.

dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\USER\Desktop\SmtpTelegramRelay
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 session created
dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 command EHLO: DomainOrAddress=localhost

dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 command MAIL: Address=test@test.com Parameters=

dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 command RCPT: Address=test1@test.com

dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 command DATA

dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 command QUIT

dbug: SmtpTelegramRelay.Relay[0]
      192.168.6.12:41782 session completed

Can you help me?

**Comment by 7orlum** [comment]
It turns out that you need to add a minus in front of the Telegram chat ID if the chat is a group or channel. Try it.
And I'll make a new version tonight where you can specify not only the chat ID, but also its @username This will make it easier to specify channels and users, but not groups unfortunately, they don't have @usernames.

**Comment by 7orlum** [comment]
Try new release https://github.com/7orlum/SmtpTelegramGateway/releases/tag/v3.0

Some new details:
If you specify a Telegram user chat, the user must be subscribed to the bot.
If you specify a Telegram group chat, you may need to add a minus sign prior to the group id, the bot must be added to the group.
If you specify a Telegram channel chat, you may need to add -100 prior to the channel id, the bot must be added to the channel admins and given the right "Post in the channel". For public channel chat, you can specify the channel public @username instead of the channel id.

**Comment by Titintgn** [comment]
Thanks, I did have the group thing - but it didn't work in the previous version.

It works perfectly in the new version. Thank you very much!!!
